PS1="[\033[1mbash\033[0m \t] "

# To disable time-stamp uncomment a line below
# PS1=""

PS1+="\033[38;5;112m\W\033[0m $ "

alias ls="ls --color=no"

source $HOME/.termux-setting/sources/extensions


